### PR TITLE
 Support basePath in getUrl() #58

### PR DESCRIPTION
**Pull request by pmi**

### CODE REVIEW

**Review by poi33 — APPROVED** [review]
https://github.com/vercel/next.js/discussions/16047#discussioncomment-48947
> No—they are not safe to use, anything you import from dist/... is considered private and may break or change at any time.

Are you sure you want to use this?

**Comment by pmi** [comment]
> [vercel/next.js#16047 (comment)](https://github.com/vercel/next.js/discussions/16047#discussioncomment-48947)
> 
> > No—they are not safe to use, anything you import from dist/... is considered private and may break or change at any time.
> 
> Are you sure you want to use this?

Good point, didn't know that !

Will use this instead: 
```
const { basePath } = useRouter();
```

**Comment by poi33** [comment]
@pmi if you make changes to a pull request we would still need a new review 👀 
So we don't just push a commit to master without another person looking at the code

**Comment by pmi** [comment]
Right, but I made changes you suggested, so I assumed you would be ok with them :)

**Comment by poi33** [comment]
I am okay with them :P Still the need approval 😁

**Pull request merged**
